IMS.WWW.ControlCenter/Controllers/OnSiteOperatorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IMS.DataAccess;
using Microsoft.WindowsAzure.StorageClient;
using Microsoft.WindowsAzure;
using System.Configuration;
using Microsoft.WindowsAzure.ServiceRuntime;
namespace IMS.WWW.ControlCenter.Controllers
{
	public class OnSiteOperatorsController : Controller
	{
		private IMSORMModelContainer _context = new IMSORMModelContainer();
		public OnSiteOperatorsController()
		{
			if (!_context.DatabaseExists())
				_context.CreateDatabase();
		}

		private OnSiteOperator GetOperatorByID(Guid id)
		{
			return _context.OnSiteOperators.First(op => op.OperatorID == id);
		}


		//
		// GET: /OnSiteOperators/

		public ActionResult Index()
		{
			var osOperators = _context.OnSiteOperators.ToList();
			ViewData.Model = osOperators;
			return View("List");
		}

		//
		// GET: /OnSiteOperators/Details/5

		public ActionResult Details(Guid id)
		{
			var osOperator = GetOperatorByID(id);
			ViewData.Model = osOperator;
			return View();
		}

		//
		// GET: /OnSiteOperators/Create

		public ActionResult Create()
		{
			return View();
		}

		//
		// POST: /OnSiteOperators/Create

		[HttpPost]
		public ActionResult Create(OnSiteOperator osOperator)
		{
			try {
				osOperator.OperatorID = Guid.NewGuid();
				_context.OnSiteOperators.AddObject(osOperator);
				_context.SaveChanges();
				return RedirectToAction("Index");
			} catch {
				return Content("Something went wrong");
			}
		}

		//
		// GET: /OnSiteOperators/Edit/5

		public ActionResult Edit(Guid id)
		{
			var osOperator = GetOperatorByID(id);
			ViewData.Model = osOperator;
			return View();
		}

		//
		// POST: /OnSiteOperators/Edit/5

		[HttpPost]
		public ActionResult Edit(Guid id, OnSiteOperator osOperator)
		{
			try {
				var old = GetOperatorByID(id);
				old.Name = osOperator.Name;
				_context.SaveChanges();
				return RedirectToAction("Index");
			} catch {
				return Content("Something went wrong");
			}
		}

		//
		// GET: /OnSiteOperators/Delete/5
		public ActionResult Delete(Guid id)
		{
			var osOperator = GetOperatorByID(id);
			ViewData.Model = osOperator;
			return View();
		}

		//
		// POST: /OnSiteOperators/Delete/5

		[HttpPost]
		public ActionResult Delete(OnSiteOperator osOperator)
		{
			try {
				// TODO: Add delete logic here
				_context.OnSiteOperators.DeleteObject(GetOperatorByID(osOperator.OperatorID));
				_context.SaveChanges();
				return RedirectToAction("Index");
			} catch {
				return Content("Something went wrong");
			}
		}
	}
}

IMS.WWW.ControlCenter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui.js")" type="text/javascript"></script>
    @RenderSection(name: "Imports", required: false)
</head>

<body>
    <div class="page">

        <div id="header">
            <div id="title">
                <h1>My MVC Application</h1>
            </div>

            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>

            <div id="menucontainer">

                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Reports", "Index", "Reports")</li>
                    <li>@Html.ActionLink("Operators", "Index", "OnSiteOperators")</li>
                </ul>

            </div>
        </div>

        <div id="main">
            <h2 class="centered">
                @ViewBag.Title
            </h2>
            <div id="master-container">
                @RenderBody()
            </div>
            <div id="detail-container">
                <div id="detail-inner">
                    <h3 class="no-selection-placeholder">No Item Selected</h3>
                </div>
            </div>
            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>

IMS.WWW.ControlCenter/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <b>@Context.User.Identity.Name</b>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}